### ISSUE TITLE
Evolution chain from Pokemon call

### ISSUE THREAD

**Issue by mildrenben** [phalt/pokeapi#109]
Hey!

The evolution chain seems quite strange to me - the id it takes doesn't really function as one would expect. I would expect an id of 1,2 or 3 to all refer to the bulbasaur line, but they don't.

I see how it works, I just wouldn't know how to figure this id out from a standard Pokemon call (api/v2/pokemon/{id or name}).

How would I obtain the evolution chain from a Pokemon call?

**Comment by zaneadix** [comment]
@mildrenben you would have to get it from a Pokemon-species call. Pokemon species should really be the basis of any Pokemon search.

If someone can think of a better way to reference chains I wouldn't be against it though I don't want to change a lot since people are starting to develop against the service

**Comment by mildrenben** [comment]
It just seems inefficient that for a 'full' Pokemon call I effectively need to make at least 3 calls. Pokemon (standard), Pokemon species and then Pokemon evolution chain.

**Comment by zaneadix** [comment]
@mildrenben I feel you but pokemon-species really are a valid logical separation from pokemon and I considered having them all be one call but a call to a pokemon resource is expensive because of the moves associated with it. They take a while to build out so it could potentially make pokemon-species calls way too expensive. Making asynchronous calls to multiple resources at once is much more efficient. Also, caching on your end would solve the problem if you intend for heavy use.

**Comment by phalt** [comment]
@mildrenben Hey :) Thanks for the query. I totally see your point about the extra calls needed for what you or I would consider "simple data", but I think that due to a confusion about what this API is. It's a data service, with related resources. I feel what you're describing is more application-specific, rather than data-specific. If we tied the data to a particular use case, we'd have people questioning why it's not tailored for another use case. It's hard to make everyone happy, but we believe being application-agnostic and just providing raw data is the best option for what this API should do.

**Comment by mildrenben** [comment]
Hey guys @zaneadix @phalt . I completely see where your coming from and appreciate the responses. I get that your trying to be app agnostic, but it does feel you've gone so far away from V1. Is there any reason for the seemingly opposite direction to v1 you've taken? (Genuinely curious).

Also - will v1 be updated for newly released games and stuff? It seems more suited to my needs but I didn't want to use it in fear it's deprecated. 

I have been meaning to set up a Redis cache to house all this anyway due to the 300 per day call limit, so I guess I'll do that. 

Cheers guys. Great resource.

**Comment by phalt** [comment]
@mildrenben Hey Ben, thanks for replying.

V1 is now deprecated, so it will no longer have anymore data added to it. V2 was originally designed to be a whole new API with new data structures and additional data sets, hence why it is formatted differently. V1 was mostly just me deciding how to structure the data, but V2 is based around how the games actually structure their data.
