### ISSUE TITLE
Regular to Mega evolution mapping?

### ISSUE THREAD

**Issue by smasher164** [phalt/pokeapi#116]
I was wondering if there was a resource that directly mapped a pokemon to its mega-evolution. For example, Venusaur's resource at [/pokemon/3/](http://pokeapi.co/api/v2/pokemon/3/) would map to Mega Venusaur's resource at [/pokemon/10033/](http://pokeapi.co/api/v2/pokemon/10033/).

I think that the `forms` object for a pokemon should list all of its forms, whether it's a regular evolution (Ivysaur to Venusaur), mega evolution (Venusaur to Mega-Venusaur), or alternate form (Rotom, Rotom-Heat, etc.) 

This will make jumping between pokemon forms much easier, and will be useful for querying its evolution data without knowing specifics like the id or name. That's just a suggestion, any thoughts?

**Comment by zaneadix** [comment]
@smasher164  checkout the pokemon-species/3/ under the varieties parameter. Anything with a mega evolution should list their mega "form" here. Mega's are a bit odd because they're technically not forms or evolutions. evolutions can be found on the evolution chain of the pokemon-species resource. I'm always open to discussing this stuff further though because some of the data I do believe is a little "iffy" in implementation. I've stuck with the veekun dataset pretty much exactly as it is because I've found they usually have solid reasons for doing things the way they did.

**Comment by smasher164** [comment]
@zaneadix Thank you so much for responding, this helps quite a bit! I was just hoping to put in a suggestion for a more clear way to jump from a pokemon to its mega-evolution. I took a look at veekun's site and noticed that they list a mega-evolution under "forms", both in the UI (http://veekun.com/dex/pokemon/venusaur#forms) and a query-string parameter (http://veekun.com/dex/pokemon/venusaur?form=mega).

Do you think that maybe merging forms with varieties is a good idea? I wasn't able to understand a clear difference between the two.

**Comment by matthewdias** [comment]
I think the data model is fine here, but I would suggest renaming:

1. `forms` in /pokemon/ to `form` since AFAIK it only contains the form that the given pokemon matches with
2. `varieties` in /pokemon-species/ to `forms` to avoid confusion

**Comment by phalt** [comment]
Renaming attributes is tricky with public APIs - we break every single integration if we do that. D:

**Comment by zaneadix** [comment]
@matthewdias there are some pokemon that will have a list.
http://pokeapi.co/api/v2/pokemon/unown/
unknown for instance lists every letter form.

The forms/varieties are tricky and a little weird from what I've seen in Veekun's data. If anyone would be willing to dig around in https://github.com/veekun/pokedex and see what exactly is the reasoning behind all of the relationships  and bring some findings back here maybe we could do some re-org (most likely not of the param names though). I did quite a bit of digging through veekun's repo but honestly things can get dense and I found my brain melting while reading late at night too often so I just went with what we got out of the box.

**Comment by matthewdias** [comment]
@zaneadix Haven't poked around too much, but it seems like the unown forms (are there any others like these?) are listed under the pokemon resource for 201, because they only look different and don't have any different stat information or anything like that. So I guess forms are different versions of the pokemon, whereas varieties are different versions of the species?

**Comment by phalt** [comment]
Can I again urge that changing attributes will _break every single integration that relies on those attributes_. We are not removing any attributes in the APIs that are currently live. If we make changes we should alias them and keep the duplicates.

**Comment by matthewdias** [comment]
It's not a huge issue. It's fairly trivial to make the second request, so if it would break too many things its probably fine to leave it as is. It just makes more sense from an organization standpoint. Guess we can close this one?

**Comment by smasher164** [comment]
After looking at the data-set, it's clear that we can access **/pokemon-species/** in the same way we access **/pokemon-form/**. This solves my problem, and is a good way to jump to a mega. I'll withdraw this issue, thank you! :smile:
