### ISSUE TITLE
Add an 'extended' parameter

### ISSUE THREAD

**Issue by MaxHasADHD** [phalt/pokeapi#122]
I think it would be beneficial to add a 'extended' parameter that can fetch more information.

When fetching all berries using `http://pokeapi.co/api/v2/berry/` It fetches all the berries but only includes the name, and a URL to fetch the information for each. So in total I would have to make 65 requests to fetch everything about berries. 

Another API I use (for something completely different though) use a parameter 'extended' which defaults to `min` which only returns limited information, and then passing in `full` would fetch all information. Something like this could be really cool I think and reduce number of requests made, at least for me.

**Comment by zaneadix** [comment]
@MaxHasADHD I've thought about this too. It' honestly wouldn't be very hard to do I believe.

https://github.com/phalt/pokeapi/blob/master/pokemon_v2/api.py

changing the ListOrDetailSerialRelation class to use the detail serializer based off of an 'extended=true' query param would most likely have exactly the desired result. My only reservation with this is the possibility of very expensive calls on larger resources like Pokemon-Species.

@phalt Have any thoughts about this one?

**Comment by MaxHasADHD** [comment]
Ya, I can see the downside of using it. For me, I am working on a iOS app (and wrapper for this API, which will be released when its done) and on launch it would be easier to make 1 or so request for all berries and items (or a few using pagination), but making 1 request to know about what exists, then 1 request per item is a lot. Just with Pokemon thats 784 right now. Seems faster to make a few request, fetch like 30 Pokemon with full detail than 1 request per to cache everything.

**Comment by phalt** [comment]
@zaneadix @MaxHasADHD I really prefer trying to make this API as agnostic as possible. There is always a tendency to introduce a feature for a specific use case, but that only opens up the floodgates for many more features and then suddenly the API has all these edge cases and things that are hard to document.

The argument for mobile applications doing fewer requests is one I hear every day in my day job, so I totally understand the reason for this. However, as Zane pointed out. Would you rather have a slow user experience because we've chucked everything into one gigantic request? Async calls are trickier to manage but make for a nicer experience. The API wrapper is just a wrapper - it shouldn't need to worry about application logic?
