### ISSUE TITLE
Magikarp and Zubat resources are very slow

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#178]
as are any other resources that have many appearance locations and related attributes.

Help optimising these will help to reduce the load times for these resources.

**Comment by mjhayes412** [comment]
Providing data for every game version seems to be the cause of `get_pokemon_moves` and `get_encountrers` being so expensive.  This will only get worse when new generations are introduced.  Would it be best to provide only the most recent game version data for `PokemonDetailSerializer` instead of everything?  Is it possible to have something like //pokeapi.co/api/v2/pokemon/41/generation1 to get details for Zubat specifically for generation 1?

**Comment by phalt** [comment]
@mjhayes412 the solution you mention is similar to #180 :) I think that's the right way to go to solve this

**Comment by phalt** [comment]
Fixed these with a recent PR
