### ISSUE TITLE
Ability endpoint doesn't return description

### ISSUE THREAD

**Issue by joshvickerson** [phalt/pokeapi#54]
According to the documentation, the abilities endpoint should return a description of the ability queried, but the description field is returning as an empty string. Were the descriptions never added to the databases or is this an error?

**Comment by zaneadix** [comment]
Yes version 1 falls short on ability descriptions but unfortunately we're not going to be fixing this for V1 as its deprecated. V2 most definitely will have ability descriptions. 

I'm considering compiling a list of what V1 is missing so we could maybe put it in the README so that in the future people in your position will have faster answers.
