### ISSUE TITLE
Getting v2 data via API?

### ISSUE THREAD

**Issue by lazerwalker** [phalt/pokeapi#57]
First of all, thanks for making this!

I just set up a local copy of the app, including loading the v2 data, as per the readme. However, I'm a bit at a loss for how to actually get the API to spit out that data for me.

It looks like only v1 API endpoints exist (e.g. `/api/v1/pokemon/1`), as trying to go to any URL with either `v2` instead of `v1` or no version in the path at all (e.g. `/api/v2/pokemon/1` or `/api/pokemon/1`) results in a 404. When I go to a valid v1 URL, I get a database error that the correct table doesn't actually exist, which suggests to me that might in fact be trying to load from v1 data (which I presumably don't have loaded).

I'm not exactly sure what the root cause of my problem is: do v2 endpoints just not exist yet? Do they exist, but I just don't know the proper URL schema? Are v1 endpoints supposed to return v2 data but my local setup is somehow incorrect? Any insight you have would be greatly appreciated.

**Comment by zaneadix** [comment]
Hey man, thanks for jumping in.

There currently are no v2 resources in this repository. We're probably going to merge them in soon.

**Comment by zaneadix** [comment]
@lazerwalker Had a chance to check any of this out?

**Comment by lazerwalker** [comment]
Alas, I haven't yet. 

What I'm hoping to do is rather specific – I'm trying to train up a neural network, and I just need to get a few specific db fields joined and dumped into a format I can more easily use. To be honest, for my research purposes just writing my own simple script that operates on the sqlite db and fetches the exact data I need is probably going to be faster than trying to get a WIP branch up and running and seeing what is and isn't implemented yet.

If I find myself with some spare cycles I'd love to peek at the in-progress stuff, but I can't make any promises...

**Comment by nightpool** [comment]
I'm confused—people are being told to upgrade, but there's no upgrade path? The messaging in the repo seems inconsistent.

**Comment by lazerwalker** [comment]
Exactly. As far as I can tell, as the repo currently stands, 

* v1 endpoints exist, but v1 data does NOT
* v2 data exists, but v2 data does NOT.

There seem to be three ways to actually get data out of this project:

1. Use the existing web-based API
2. Use [this](https://github.com/zaneadix/pokeapi/tree/rest-framework) branch, which contains endpoints for some (but NOT all) v2 data
3. Manually deal with the raw data yourself, either by parsing the v2 CSV files or by running the import script and dealing with the resulting SQLite database.

It would be wonderful if someone wanted to update the README to reflect the fact that the repo is not currently in workable shape.

**Comment by nightpool** [comment]
@thepsionic you probably want in on this thread

**Comment by zaneadix** [comment]
I was wondering about the v1 data as well and took some time to sort that out. I updated the README a about 3 weeks ago to show to how to make use of it.

All work I've done for v2 data has also been merged into the master branch. Its still a work in progress. Probably about 75% of data is being served. Its a TON more data than what v1 was dealing with so theres still quite a ways to go with it but pretty most things of heavy interest have been dealt with.

@lazerwalker @nightpool Is there anything I could do to help you out or clarify whats going on?  Work on the project is moving super fast just because of life. I've paused on writing the rest of the v2 endpoints to write tests for whats in place currently.

What exactly do you feel like is coming up short in the readme? i'd be happy to take some time to work out some answers for you.

**Comment by ThePsionic** [comment]
@zaneadix, just to confirm, these pages are not yet served via http://pokeapi.co correct?

**Comment by zaneadix** [comment]
Correct. Only when run locally. V2 is still very much a WIP.

**Comment by darsh2** [comment]
Any expected date by which V2 would be served via http://pokeapi.co ?

**Comment by phalt** [comment]
@darsh2 @zaneadix working on it this week during the holiday break.
