### ISSUE TITLE
Make /api/v2/characteristic/ return characteristic descriptions

### ISSUE THREAD

**Issue by OrangeCrush** [phalt/pokeapi#84]
I think that it would be useful to have /api/v2/characteristic/ return the characteristic descriptions as well as the url's.

As a end user it's nice to be able to grab all names of a given resource at one time.

If I get time, I would be interested in implementing this myself.

**Comment by phalt** [comment]
@OrangeCrush do you mean having hyperlinks to other resources?

**Comment by zaneadix** [comment]
@phalt @OrangeCrush I believe you mean to include them in the list view? As of now characteristics aren't "named" resources so they're just returned as a list of objects with a single url parameter
```
[
    {"url":"http://beta.pokeapi.co/api/v2/characteristic/1/"},
    {"url":"http://beta.pokeapi.co/api/v2/characteristic/2/"},
...
]
```
And you want them to return the description.
This might be something we could do. I have felt like just having urls from resources without a name value is a bit of a waste but the description field also isn't just a simple string value the the name is. I was trying to keep from having complex objects in the list-style payload but that might have been a failing on my part.

**Comment by phalt** [comment]
@OrangeCrush @zaneadix Generally, I prefer against adding in extra tidbits in these types of relationships. One person can argue that _"Having the name there is useful for my app"_ and so I'll add it, but then some can argue that _"Having the description would be useful for me too!"_ and before you know it, you have nested resources and it gets complicated.

I think we should stick to hypermedia and true RESTful-ness in order to keep the resources separate and more flexible. I understand this means more requests for clients, but requests are not expensive.

**Comment by OrangeCrush** [comment]
Yeah I'm talking about including some kind of name in the "list view" of the characteristic.

```json
    "results": [
        {
            "name": "bulbasaur",
            "url": "http://pokemon.com:8000/api/v2/pokemon/1/"
        },
```

I agree that we don't want to go crazy and make the list views return a ton of data, but when you look at the other list view resources, most of them I have used return at least "name" (nature, pokemon, move, stat, etc).

Do we think it makes sense to have the characteristic resource be "named"?  I can't think of another option for the name of a characteristic outside of "Alert to sounds", or "Mischievous"

Thanks!

**Comment by zaneadix** [comment]
@phalt that's pretty much where I was coming from (you just put it far more eloquently).

@OrangeCrush The reason these resources have names  is simply because they have names in the data provided by veekun. A good portion of their models have names for identification unless they (for whatever reason) didn't see need for them. I also considered adding names to the characteristics but they would have been clunky and I'd really like to keep from modifying the data so we don't have to manage that sort of thing on our end. Also, the biggest reason I included names in the resource listings like the one you referenced above for bulbasaur is because that resource is can be referenced by name
e.g.
```
http://pokemon.com:8000/api/v2/pokemon/1/
or
http://pokemon.com:8000/api/v2/pokemon/bulbasaur/
```
We wouldn't be able to do the same thing with descriptions. 
I hate to be a a bummer but your issue (most likely) should really be handled by caching on your end.

**Comment by zaneadix** [comment]
For reference, there are only 3 resources that do not return names.

Characteristics - These could be build from the english descriptions ("Takes plenty of Siestas" would become "takes-plenty-of-sientas"). This honestly wouldn't be a bad idea. Like I said earlier I just thought it was pretty clunky but it might just be more consistent with the rest of the api. I actually had to do something similar for berries.

Evolution Chains - These are just really complex objects built at runtime, so there was no name for them in the csv's (because they technically don't exist in them). I considered for a while giving them names like "bulbasaur-family" but didn't get too deep into thought about it.

Location Areas - These actually do have names, the problem is that they are not unique so multiple caves in the games would have areas called "floor-1". They could be renamed something like "terminus-cave-floor-1"

These all might be worth doing for the sake of consistency in the API. I just didn't want to make the call myself and figured if people really wanted them they would ask. I think solving these naming issues could be a nice compromise to your issue. If you agree then I would encourage you to create another issue referencing these and we'll see if others agree. They wouldn't be hard to fix. Generating names for these resources would need to take place during the db build phase.
