### ISSUE TITLE
Identical Move Records Getting Sent Multiple Times in Summary

### ISSUE THREAD

**Issue by SiMylo** [phalt/pokeapi#85]
I've noticed that if a move has different learn levels in different version groups, the exact same move record will be copied multiple times when listing a pokemon's learnset.  This appears to be because the query sorts by 'level' before looking for distinct 'move_id' values.  According to Django documentation, this will happen because internally it's keeping track of the level so each entry looks different.  I have a fix for this locally, but I have no idea how to testing.  Should I submit a pull request, or can someone point me to a decent primer on how our testing framework works?

**Comment by phalt** [comment]
@SiMylo Hey, thanks for raising this.

Is this for V1 or V2?

**Comment by zaneadix** [comment]
From the description it sounds like it would be V2. @SiMylo Would you be able to post an example of the bug here? I'm just interested :) As far as tests go you could checkout tests.py in pokemon_v2 and look the `setup_pokemon_move_data` method and the `test_pokemon_api` method. You could most likely test to make sure your fix works just by adding a few moves with the same name, different version group and different learn level and then assert the results.

**Comment by SiMylo** [comment]
@phalt this is for V2.  I'll be more specific next time.

@zaneadix If you search for "thunder-wave" in the following file you can see 5 copies get returned from api/v2/pokemon/25/ .  I will check out those files and see if I can get it tested and then submit a pull request.
[api.v2.pokemon.25.txt](https://github.com/phalt/pokeapi/files/114263/api.v2.pokemon.25.txt)

**Comment by zaneadix** [comment]
Sure enough. Nice catch @SiMylo. Thanks for the taking this on :)

**Comment by zaneadix** [comment]
#88 takes care of this. Thanks @SiMylo!
