### ISSUE TITLE
CSV to database builder

### ISSUE THREAD

**Issue by phalt** [phalt/pokeapi#9]
We need to implement a new way of taking CSV data and turning it into database tables, whilst still ensuring the V2 models can communicate with the data correctly.

**Comment by vamsivarikuti** [comment]
Can you be more specific about this task. I like to work on it.

**Comment by zaneadix** [comment]
I second that. I see where you mention your previous implementation wasn't ideal. How should things change? Would it be efficient enough to just consolidate everything into a single script rather than individual functions?

**Comment by phalt** [comment]
There is a rich collection of data over on Veekun's [pokedex](https://github.com/veekun/pokedex), which is all exported to csv.

Veekun's pokedex transforms this all into a mysql (I think?) database at run time. Ideally we'd want a similar script that powers through all those scripts and maps them to the models that we have in PokéAPI. They are slightly different, with slightly different relationships. This is again due to my initial design, which was nothing more than 5 minutes of "that'll do" to get the relationships to work (remember PokeAPI was a weekend project that span out of control :D ).

It might be a good idea to build some abstract models that map to Veekun's CSV files better but still allows the old V1 API to work nicely.

**Comment by aindurti** [comment]
I agree with CSV approach. Querying it is much faster, and the format is way more lightweight for large sets of data. It removes repetitive keyframes, and although development on it can be a little challenging because there isn't much standardization, the API itself will take care of that.

Mapping with the old V1 API might be easier as well, provided we upgrade the returned object to something more business-logicky (more relational/tabular). Try using ODATA, a version of JSON that allows for more powerful querying for large data-sets.


The hard part of mapping with the old API will be allowing conditional inputs to the requests that allow for better filtration. See issue #28

**Comment by phalt** [comment]
@aindurti Just to be clear - I don't want to make CSV files the datastore here, I want to use them to generate the datastore on the server by creating database rows. Querying CSV files will put a lock on that file while it is being read. This is undesirable considering the amount of traffic PokéAPI receives, it will cause broken requests.

**Comment by zaneadix** [comment]
Pull request #35 should hopefully take care of this.

**Comment by matthewdias** [comment]
This might be out of context because I haven't been following this project very closely, but as I understand, V2 is supposed to map closer to the models used by Veekun. In that case, many database apps provide export from SQL to JSON. Could that be of any use here if we were to pull the database straight from Veekun?

**Comment by zaneadix** [comment]
Taken care of in pull request #40

**Comment by Brisingr211** [comment]
Could they load the E-R model of the database? (.jpg, .png)

**Comment by RokieTheJawa** [comment]
Which csv contains the full URL for v5 png images on PókeAPI?

**Comment by Naramsim** [comment]
none i guess
