### ISSUE TITLE
Plans for Pokèmon GO data?

### ISSUE THREAD

**Issue by skylarjhdownes** [phalt/pokeapi#90]
Perhaps it's a bit premature, but has there been any discussion around data related to Pokèmon GO?  Capture locations/coordinates/zones would be extremely useful if we could find a way to get good data.  Presumably there will be other data unique to the game.  It might be better for GO to have a separate API though, I'm not sure.  Thoughts?

**Comment by zaneadix** [comment]
We don't have any current plans for anything like this. It would be a huge undertaking since we're currently using a data source we didn't have to create. By no means would I say it's out of the question though. If someone was willing to build this sort of data out I'd be into it. Actually Veekun's repo also has a data for pokemon conquest that I didn't pull into this project because I personally felt like it was out of scope (I also just don't know anything about the game other than it looks fun). 

One thing we'd really like to do is card game data. Really, I'd love to see just about anything pokemon data related to become available. Either way this sort of thing would probably involve some project restructuring.

**Comment by tdmalone** [comment]
Just thought I'd ask about this again, being a lot later in the piece now. There's lots of data available online about Pokemon Go specific movesets and that sort of thing - the mechanics can be quite different to the traditional Pokemon games. Would this fit into the API structure at all?

**Comment by zaneadix** [comment]
@tdmalone I don't think there's any plans for this to ever really contain 'go' data. I personally believe there would need to be a separate API if anyone would be interested in doing that. It wouldn;t be good to try and mash them together.

**Comment by tdmalone** [comment]
Ok, fair enough. I guess I was thinking something simple like extra properties on each Pokemon for things like max_cp, egg_distance, buddy_distance, candy_to_evolve, possible_movesets, etc., all of which are available in JSON format already at The Silph Road (although not as a well documented API.) I do admit I have not considered how this interacts with the API structure as a whole, though - particularly the individual move objects, and now that for some Pokemon it's not just candy you need to evolve them.
